-- Executar manualmente no SQL Editor durante uma pausa nos atendimentos.
-- Faça backup do banco antes. Depois deste SQL, reinicie com o backend novo.
-- Preserva IDs, protocolos, mensagens, anexos e config.supportTickets como cópia.
BEGIN;
LOCK TABLE public.config IN SHARE ROW EXCLUSIVE MODE;

CREATE TABLE IF NOT EXISTS public.fenix_support_tickets (
  id text PRIMARY KEY,
  numero bigint GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  payload jsonb NOT NULL CHECK (jsonb_typeof(payload) = 'object')
);
CREATE TABLE IF NOT EXISTS public.fenix_support_messages (
  id text PRIMARY KEY,
  ticket_id text NOT NULL REFERENCES public.fenix_support_tickets(id) ON DELETE CASCADE,
  ordem bigint GENERATED ALWAYS AS IDENTITY UNIQUE NOT NULL,
  payload jsonb NOT NULL CHECK (jsonb_typeof(payload) = 'object')
);
CREATE INDEX IF NOT EXISTS fenix_support_messages_ticket_idx ON public.fenix_support_messages(ticket_id, ordem);
CREATE TABLE IF NOT EXISTS public.fenix_support_migrations (version integer PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());

ALTER TABLE public.fenix_support_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fenix_support_messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.fenix_support_migrations ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.fenix_support_tickets, public.fenix_support_messages, public.fenix_support_migrations FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.fenix_support_tickets, public.fenix_support_messages, public.fenix_support_migrations TO service_role;
REVOKE ALL ON SEQUENCE public.fenix_support_tickets_numero_seq, public.fenix_support_messages_ordem_seq FROM PUBLIC, anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.fenix_support_tickets_numero_seq, public.fenix_support_messages_ordem_seq TO service_role;
GRANT UPDATE ON SEQUENCE public.fenix_support_tickets_numero_seq TO service_role;

DO $$
DECLARE legacy jsonb; ticket jsonb; msg jsonb; maximum bigint;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.fenix_support_migrations WHERE version = 1) THEN
    SELECT value::jsonb INTO legacy FROM public.config WHERE key = 'supportTickets';
    legacy := coalesce(legacy, '[]'::jsonb);
    IF jsonb_typeof(legacy) <> 'array' THEN RAISE EXCEPTION 'supportTickets não é uma lista; migração cancelada.'; END IF;
    FOR ticket IN SELECT value FROM jsonb_array_elements(legacy) LOOP
      INSERT INTO public.fenix_support_tickets(id, numero, payload)
        VALUES (ticket->>'id', (ticket->>'numero')::bigint, ticket - 'id' - 'numero' - 'mensagens');
      FOR msg IN SELECT value FROM jsonb_array_elements(coalesce(ticket->'mensagens', '[]'::jsonb)) LOOP
        INSERT INTO public.fenix_support_messages(id, ticket_id, payload)
          VALUES (msg->>'id', ticket->>'id', msg - 'id');
      END LOOP;
    END LOOP;
    SELECT max(numero) INTO maximum FROM public.fenix_support_tickets;
    PERFORM setval(pg_get_serial_sequence('public.fenix_support_tickets','numero'), coalesce(greatest(maximum, 1),1), maximum IS NOT NULL);
    INSERT INTO public.fenix_support_migrations(version) VALUES (1);
  END IF;
END $$;

CREATE OR REPLACE FUNCTION public.fenix_support_ticket_json(p_id text) RETURNS jsonb
LANGUAGE sql STABLE SECURITY INVOKER SET search_path = public, pg_temp AS $$
  SELECT t.payload || jsonb_build_object('id',t.id,'numero',t.numero,'mensagens',
    coalesce((SELECT jsonb_agg(m.payload || jsonb_build_object('id',m.id) ORDER BY m.ordem)
      FROM public.fenix_support_messages m WHERE m.ticket_id=t.id), '[]'::jsonb))
  FROM public.fenix_support_tickets t WHERE t.id=p_id;
$$;

CREATE OR REPLACE FUNCTION public.fenix_support_action(p_action text, p_data jsonb DEFAULT '{}'::jsonb) RETURNS jsonb
LANGUAGE plpgsql SECURITY INVOKER SET search_path = public, pg_temp AS $$
DECLARE current_ticket public.fenix_support_tickets%ROWTYPE; state text; target text;
  stamp text := to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');
  result jsonb; terminal boolean; restore_ticket jsonb; restore_message jsonb; max_number bigint;
BEGIN
  IF p_action = 'list' THEN
    SELECT coalesce(jsonb_agg(public.fenix_support_ticket_json(id) ORDER BY numero DESC), '[]'::jsonb)
      INTO result FROM public.fenix_support_tickets;
    RETURN result;
  ELSIF p_action = 'get' THEN
    RETURN public.fenix_support_ticket_json(p_data->>'id');
  ELSIF p_action = 'restore' THEN
    IF jsonb_typeof(p_data->'tickets') IS DISTINCT FROM 'array' THEN RAISE EXCEPTION 'Backup de suporte inválido.'; END IF;
    LOCK TABLE public.fenix_support_tickets IN SHARE ROW EXCLUSIVE MODE;
    IF NOT coalesce((p_data->>'merge')::boolean,false) THEN DELETE FROM public.fenix_support_tickets; END IF;
    FOR restore_ticket IN SELECT value FROM jsonb_array_elements(p_data->'tickets') LOOP
      -- Merge preserves tickets already present, including their newer messages.
      IF coalesce((p_data->>'merge')::boolean,false) AND EXISTS
        (SELECT 1 FROM public.fenix_support_tickets WHERE id=restore_ticket->>'id') THEN CONTINUE; END IF;
      INSERT INTO public.fenix_support_tickets(id,numero,payload) VALUES(restore_ticket->>'id',
        (restore_ticket->>'numero')::bigint, restore_ticket - 'id' - 'numero' - 'mensagens');
      FOR restore_message IN SELECT value FROM jsonb_array_elements(coalesce(restore_ticket->'mensagens','[]'::jsonb)) LOOP
        INSERT INTO public.fenix_support_messages(id,ticket_id,payload)
          VALUES(restore_message->>'id',restore_ticket->>'id',restore_message - 'id');
      END LOOP;
    END LOOP;
    SELECT max(numero) INTO max_number FROM public.fenix_support_tickets;
    -- Never move a live sequence backwards, including when restoring older backups.
    PERFORM setval(pg_get_serial_sequence('public.fenix_support_tickets','numero'),
      greatest(coalesce(max_number,1),(SELECT last_value FROM public.fenix_support_tickets_numero_seq)),true);
    RETURN jsonb_build_object('success',true);
  ELSIF p_action = 'clear' THEN
    DELETE FROM public.fenix_support_tickets;
    RETURN jsonb_build_object('success',true);
  ELSIF p_action = 'create' THEN
    IF coalesce(length(btrim(p_data->>'assunto')),0) NOT BETWEEN 1 AND 200
       OR coalesce(length(btrim(p_data->>'texto')),0) NOT BETWEEN 1 AND 5000
       OR coalesce(p_data->>'actor','') = '' THEN
      RAISE EXCEPTION 'Informe assunto e mensagem válidos.';
    END IF;
    INSERT INTO public.fenix_support_tickets(id,payload) VALUES(p_data->>'id',jsonb_build_object(
      'assunto',btrim(p_data->>'assunto'),'status','aberto','criadoPor',p_data->>'actor',
      'criadoPorNome',p_data->>'actorName','criadoEm',stamp,'atualizadoEm',stamp));
    INSERT INTO public.fenix_support_messages(id,ticket_id,payload) VALUES(p_data->>'messageId',p_data->>'id',jsonb_build_object(
      'tipo','di','autorNome',p_data->>'actorName','autorRef',p_data->>'actor','texto',btrim(p_data->>'texto'),
      'criadoEm',stamp,'anexos',coalesce(p_data->'anexos','[]'::jsonb)));
    RETURN public.fenix_support_ticket_json(p_data->>'id');
  END IF;

  -- Row lock serializes status changes and messages only for this ticket.
  SELECT * INTO current_ticket FROM public.fenix_support_tickets WHERE id=p_data->>'id' FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Chamado não encontrado.'; END IF;
  state := current_ticket.payload->>'status';
  terminal := state IN ('fechado','resolvido','arquivado');
  IF p_data->>'tipo' = 'di' AND current_ticket.payload->>'criadoPor' IS DISTINCT FROM p_data->>'actor' THEN
    RAISE EXCEPTION 'Este chamado não pertence a você.';
  END IF;
  IF coalesce(p_data->>'tipo','') NOT IN ('di','suporte') THEN RAISE EXCEPTION 'Transição de situação não permitida.'; END IF;

  IF p_action = 'message' THEN
    IF terminal THEN RAISE EXCEPTION 'Este chamado está encerrado. Reabra antes de enviar uma mensagem.'; END IF;
    IF (coalesce(length(btrim(p_data->>'texto')),0)=0 AND jsonb_array_length(coalesce(p_data->'anexos','[]'::jsonb))=0)
       OR length(p_data->>'texto')>5000 THEN RAISE EXCEPTION 'Escreva a mensagem ou anexe um arquivo.'; END IF;
    INSERT INTO public.fenix_support_messages(id,ticket_id,payload) VALUES(p_data->>'messageId',current_ticket.id,jsonb_build_object(
      'tipo',p_data->>'tipo','autorNome',p_data->>'actorName','autorRef',p_data->>'actor','texto',btrim(p_data->>'texto'),
      'criadoEm',stamp,'anexos',coalesce(p_data->'anexos','[]'::jsonb)));
    target := CASE WHEN p_data->>'tipo'='suporte' THEN 'aguardando_resposta'
      WHEN state='aguardando_resposta' THEN 'aberto' ELSE state END;
    UPDATE public.fenix_support_tickets SET payload=payload || jsonb_build_object('status',target,'atualizadoEm',stamp)
      WHERE id=current_ticket.id;
  ELSIF p_action = 'status' THEN
    target := p_data->>'status';
    IF target IS NULL OR target NOT IN ('aberto','em_andamento','aguardando_resposta','resolvido','fechado','arquivado')
      THEN RAISE EXCEPTION 'Transição de situação não permitida.'; END IF;
    IF p_data->>'tipo'='di' AND NOT ((target='aberto' AND terminal) OR (target IN ('fechado','arquivado') AND NOT terminal))
      THEN RAISE EXCEPTION 'Transição de situação não permitida.'; END IF;
    UPDATE public.fenix_support_tickets SET payload=(payload - 'fechadoEm' - 'fechadoPor') ||
      jsonb_build_object('status',target,'atualizadoEm',stamp) || CASE WHEN target='fechado'
      THEN jsonb_build_object('fechadoEm',stamp,'fechadoPor',p_data->>'actorName') ELSE '{}'::jsonb END
      WHERE id=current_ticket.id;
  ELSE
    RAISE EXCEPTION 'Operação de suporte inválida.';
  END IF;
  RETURN public.fenix_support_ticket_json(current_ticket.id);
END $$;

REVOKE ALL ON FUNCTION public.fenix_support_ticket_json(text), public.fenix_support_action(text,jsonb) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.fenix_support_ticket_json(text), public.fenix_support_action(text,jsonb) TO service_role;

-- O JSON legado é somente uma cópia de recuperação após migrar. Bloqueia uma
-- instância antiga de gravar ali e confirmar mensagens que o servidor novo não vê.
CREATE OR REPLACE FUNCTION public.fenix_support_protect_legacy() RETURNS trigger
LANGUAGE plpgsql SET search_path = public, pg_temp AS $$
BEGIN
  IF NEW.key='supportTickets' THEN RAISE EXCEPTION 'Suporte migrado: atualize o backend antes de enviar chamados.'; END IF;
  RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS fenix_support_legacy_readonly ON public.config;
CREATE TRIGGER fenix_support_legacy_readonly BEFORE INSERT OR UPDATE ON public.config
  FOR EACH ROW EXECUTE FUNCTION public.fenix_support_protect_legacy();
REVOKE ALL ON FUNCTION public.fenix_support_protect_legacy() FROM PUBLIC, anon, authenticated;
NOTIFY pgrst, 'reload schema';
COMMIT;

SELECT (SELECT count(*) FROM public.fenix_support_tickets) AS chamados,
       (SELECT count(*) FROM public.fenix_support_messages) AS mensagens,
       (SELECT count(*) FROM public.fenix_support_migrations WHERE version=1) AS migracao_aplicada;
-- migracao_aplicada deve ser 1. Chamados/mensagens devem corresponder ao legado
-- na primeira execução. Reexecutar este script não reimporta o JSON antigo.
