import assert from 'node:assert/strict';
import sharp from 'sharp';
import { previewWidth, resizePreview } from '../src/server/imagePreview.ts';
import { imageVariant } from '../src/utils/imageVariants.ts';
assert.equal(previewWidth({ w: '640', format: 'webp' }, false), 640);
assert.equal(previewWidth({ w: '640', format: 'webp' }, true), null);
assert.equal(previewWidth({ w: '200000', format: 'webp' }, false), null);
assert.equal(previewWidth({ w: ['640'], format: 'webp' }, false), null);
assert.equal(imageVariant('https://i.vimeocdn.com/photo', 640), 'https://i.vimeocdn.com/photo');
assert.equal(imageVariant('/api/storage/preview/a.png?download=1', 640), '/api/storage/preview/a.png?download=1');
const source = await sharp({ create: { width: 1920, height: 1080, channels: 4, background: { r: 200, g: 25, b: 90, alpha: .5 } } }).png().toBuffer();
const image = await resizePreview(source, 'image/png', 640);
const meta = await sharp(image.data).metadata();
assert.equal(image.mime, 'image/webp');
assert.equal(meta.width, 640);
assert.equal(meta.height, 360);
assert.equal(meta.hasAlpha, true);
assert.ok(image.data.length < source.length);
const pdf = Buffer.from('%PDF-original');
assert.equal((await resizePreview(pdf, 'application/pdf', 640)).data, pdf);
const bad = Buffer.from('imagem inválida');
assert.equal((await resizePreview(bad, 'image/jpeg', 640)).data, bad);
console.log('OK: imagens menores, proporção e transparência preservadas, downloads/PDFs intactos, dimensões limitadas e falha recuperável.');
